version: '3.3'

services:
  app:
    build: .
    container_name: weekendflightsparser
    command: start-wf-parser
    env_file:
     - private.env
    volumes:
     - /etc/localtime:/etc/localtime:ro
