name: Unittests

on: [push, pull_request]

jobs:
  run_pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install self modules
      run: pip install -e .
    - name: Test with pytest
      env:
        IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
        WF_BOT_TOKEN: ${{ secrets.WF_BOT_TOKEN }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        VK_OWNER_ID_GROUP: ${{ secrets.VK_OWNER_ID_GROUP }}
        DB_LOGIN: ${{ secrets.DB_LOGIN }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_ADDRESS: ${{ secrets.DB_ADDRESS }}
        TRAVELPAYOUTS_TOKEN: ${{ secrets.TRAVELPAYOUTS_TOKEN }}
      run: pytest -vvvv --cov=./wf